//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by QuoteListTools.rc
//
#define ID_LOAD_SETTING                 3
#define ID_SAVE_SETTING                 4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_QuoteListTools_DIALOG       102
#define ID_INDICATOR_STATUS             102
#define ID_INDICATOR_STATUS2            103
#define IDR_MAINFRAME                   128
#define IDD_FILTERDIALOG                129
#define IDD_TEXT                        130
#define IDD_DIALOG1                     133
#define IDD_STAT_DIALOG                 134
#define IDI_GREEN_LIGHT                 136
#define IDR_RED_FLASHING                137
#define IDD_SEND_MSG_DIALOG             138
#define IDD_LOG_SCHEDULE_DIALOG         140
#define IDD_SOCKET_SERVER_DIALOG        141
#define IDC_LIST1                       1000
#define IDC_DISPLAY1                    1001
#define IDC_CLEAR1                      1002
#define IDC_OUTPUTTOFILE                1003
#define IDC_FILENAME                    1004
#define IDC_IPADDRESS1                  1005
#define IDC_IPADDRESS3                  1006
#define IDC_PORT                        1007
#define IDC_START                       1008
#define IDC_STOP                        1009
#define IDC_IPADDRESS2                  1010
#define IDC_ADD                         1011
#define IDC_REMOVE                      1012
#define IDC_PUTDATATOCACHE              1013
#define IDC_SAVE_DATA                   1014
#define IDC_PORT2                       1015
#define IDC_PAGENO                      1016
#define IDC_SEARCH                      1017
#define IDC_LIST2                       1018
#define IDC_DROP                        1019
#define IDC_FILTER                      1020
#define IDC_CLEAR2                      1021
#define IDC_FILENAME2                   1022
#define IDC_DISPLAY2                    1023
#define IDC_FIDNO                       1023
#define IDC_OUTPUTTOFILE2               1024
#define IDC_MSGTYPE                     1024
#define IDC_RETRIEVE_DATA               1025
#define IDC_DPID                        1025
#define IDC_SEND_INTERVAL               1025
#define IDC_LIST_ALL_FIDS               1026
#define IDC_PORT3                       1027
#define IDC_COMBO2                      1028
#define IDC_LIST_ALL_DROP_FID           1028
#define IDC_START2                      1029
#define IDC_STOP2                       1030
#define IDC_LIST3                       1031
#define IDC_ADD2                        1032
#define IDC_LISTALLPAGES                1033
#define IDC_LISTALLDROPPAGES            1034
#define IDC_NO_IN_TEXT                  1034
#define IDC_ORIG_TEXT                   1035
#define IDC_REMOVE2                     1035
#define IDC_TRANSLATE                   1036
#define IDC_TEST_DROP                   1037
#define IDC_TEST                        1038
#define IDC_FID                         1039
#define IDC_TAB1                        1040
#define IDC_TAB                         1040
#define IDC_SHOW_STAT                   1041
#define IDC_FILE_MSG                    1042
#define IDC_TIMECHECK                   1043
#define IDC_COMBO1                      1045
#define IDC_SEND                        1045
#define IDC_STATISTIC_CHECK             1048
#define IDC_PAGE_EDIT                   1050
#define IDC_RETREIVE_BUTTON             1052
#define IDC_PAGE_STATIC                 1053
#define IDC_ANIMATE1                    1055
#define IDC_RESET_BUTTON                1056
#define IDC_ANIMATE2                    1056
#define IDC_REFRESH_BUTTON              1057
#define IDC_SELECTION_TEXT              1058
#define IDC_BUTTON1                     1059
#define IDC_RETRIEVE                    1059
#define IDC_MSG_DETAIL_CHECK            1060
#define IDC_SHOW_INFO_CHECK             1061
#define IDC_RETRIEVE_STOP               1062
#define IDC_FAULTS                      1067
#define IDC_STATUSLISTFLAME             1068
#define IDC_TESTDROP                    1069
#define IDC_GROUPCOMBO                  1071
#define ID_CLOSE                        1072
#define IDC_GROUPCOMBO2                 1072
#define IDC_EDIT2                       1075
#define IDC_SEND_DPID                   1075
#define IDC_RECTYPE                     1075
#define IDC_TO                          1075
#define IDC_EDIT3                       1076
#define IDC_INS                         1076
#define IDC_EXIT                        1078
#define IDC_PAGE                        1079
#define IDC_PAGE2                       1080
#define IDC_FIDVALUE                    1081
#define IDC_AUTO_2                      1082
#define IDC_AUTO_1                      1083
#define IDC_TCP_DCACHE                  1083
#define IDC_FROM                        1084
#define IDC_SOCKET                      1085
#define IDC_SERVER_STATUS               1086
#define ID_EXIT                         1090
#define IDC_REMOVE_ALL                  1092
#define IDC_SHOWQUOTELIST               1094
#define IDC_UPDATE_CHECK                1097
#define IDC_REPEAT                      1098
#define IDC_STATICGROUP_BOX             1099
#define IDC_LISTCHOICE_COMBO            1100
#define IDC_REGISTER                    1101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
